#!/bin/sh

if [ $(dig example.com | grep -E ".*\..*\..*\..*" | grep "example\.com\." | head -n 1 | cut -f6) != $(dig example.com @$dns | grep -E ".*\..*\..*\..*" | grep "example\.com\." | head -n 1 | cut -f6) ]; then
echo "dig failed, killing unbound..."
kill $(cat /usr/local/etc/unbound/unbound.pid)
exit 1
elif [ $(dig example.com | grep -E ".*\..*\..*\..*" | grep "example\.com\." | head -n 1 | cut -f6) == $(dig example.com @$dns | grep -E ".*\..*\..*\..*" | grep "example\.com\." | head -n 1 | cut -f6) ]; then
exit 0
fi
